"""Rendering tests: output validity, one-page guarantee, and the overflow guard."""

from __future__ import annotations

from datetime import date

import pytest

from pitch_analyzer.models import AnalysisResult
from pitch_analyzer.render import (
    MIN_FONT_SIZE,
    START_FONT_SIZE,
    LayoutOverflowError,
    _build_layout,
    render_one_pager,
    score_color,
)

STAMP = date(2026, 8, 10)


def _page_count(path) -> int:
    import pdfplumber

    with pdfplumber.open(str(path)) as pdf:
        return len(pdf.pages)


def _page_text(path) -> str:
    import pdfplumber

    with pdfplumber.open(str(path)) as pdf:
        return "\n".join(page.extract_text() or "" for page in pdf.pages)


# --------------------------------------------------------------------------- #
# Output basics
# --------------------------------------------------------------------------- #


def test_render_creates_a_pdf_over_5kb(tmp_path, analysis_result):
    output = tmp_path / "report.pdf"

    returned = render_one_pager(
        analysis_result, output, company_name="Acme Robotics", generated_on=STAMP
    )

    assert returned == output
    assert output.exists()
    assert output.stat().st_size > 5 * 1024


def test_output_is_exactly_one_landscape_page(tmp_path, analysis_result):
    output = tmp_path / "landscape.pdf"
    render_one_pager(analysis_result, output, generated_on=STAMP)

    import pdfplumber

    with pdfplumber.open(str(output)) as pdf:
        assert len(pdf.pages) == 1
        page = pdf.pages[0]
        assert round(page.width) == 792
        assert round(page.height) == 612


def test_portrait_orientation(tmp_path, analysis_result):
    output = tmp_path / "portrait.pdf"
    render_one_pager(
        analysis_result, output, orientation="portrait", generated_on=STAMP
    )

    import pdfplumber

    with pdfplumber.open(str(output)) as pdf:
        assert len(pdf.pages) == 1
        assert round(pdf.pages[0].width) == 612
        assert round(pdf.pages[0].height) == 792


def test_output_is_under_2mb(tmp_path, analysis_result):
    output = tmp_path / "size.pdf"
    render_one_pager(analysis_result, output, generated_on=STAMP)

    assert output.stat().st_size < 2 * 1024 * 1024


def test_bad_orientation_rejected(tmp_path, analysis_result):
    with pytest.raises(ValueError, match="landscape"):
        render_one_pager(analysis_result, tmp_path / "x.pdf", orientation="sideways")


# --------------------------------------------------------------------------- #
# Content
# --------------------------------------------------------------------------- #


def test_all_ten_category_scores_appear(tmp_path, analysis_result):
    output = tmp_path / "scores.pdf"
    render_one_pager(
        analysis_result, output, company_name="Acme Robotics", generated_on=STAMP
    )
    text = _page_text(output)

    for label, _score in analysis_result.scores.category_rows():
        assert label in text, f"missing scorecard row: {label}"


def test_key_sections_and_footer_present(tmp_path, analysis_result):
    output = tmp_path / "content.pdf"
    render_one_pager(
        analysis_result, output, company_name="Acme Robotics", generated_on=STAMP
    )
    text = _page_text(output)

    assert "Acme Robotics" in text
    assert "SCORECARD" in text
    assert "EXECUTIVE SUMMARY" in text
    assert "SCENARIOS" in text
    assert "TOP RISKS" in text
    assert "TOP 5 DILIGENCE QUESTIONS" in text
    assert "BULL CASE" in text
    assert "BEAR CASE" in text
    assert "Generated by TEN Capital Decision Intelligence" in text
    assert "2026-08-10" in text


def test_recommendation_badge_text_is_rendered(tmp_path, analysis_result):
    output = tmp_path / "badge.pdf"
    render_one_pager(analysis_result, output, generated_on=STAMP)
    text = _page_text(output)

    assert "INVESTIGATE FURTHER" in text
    assert "62% CONF." in text


@pytest.mark.parametrize(
    ("recommendation", "expected_hex"),
    [("Invest", "#16a34a"), ("Investigate Further", "#d97706"), ("Pass", "#dc2626")],
)
def test_badge_colour_matches_recommendation(
    analysis_payload, recommendation, expected_hex
):
    from pitch_analyzer.render import BADGE_COLORS, _hex

    analysis_payload["executive_summary"]["recommendation"] = recommendation
    analysis = AnalysisResult.model_validate(analysis_payload)

    color = BADGE_COLORS[analysis.executive_summary.recommendation]
    assert _hex(color) == expected_hex


def test_markup_characters_in_content_do_not_break_rendering(
    tmp_path, analysis_payload
):
    analysis_payload["bull_case"] = "Margins >50% & <2yr payback for R&D <buyers>"
    analysis_payload["executive_summary"]["investment_thesis"] = "A & B <C> \"quoted\""
    analysis = AnalysisResult.model_validate(analysis_payload)

    output = tmp_path / "escaped.pdf"
    render_one_pager(analysis, output, generated_on=STAMP)

    assert _page_count(output) == 1


def test_extra_risks_are_disclosed_not_silently_dropped(tmp_path, analysis_payload):
    extra = dict(analysis_payload["risks"][0])
    extra["description"] = "A sixth risk that will not fit in the table."
    analysis_payload["risks"] = analysis_payload["risks"] + [extra, dict(extra)]
    analysis = AnalysisResult.model_validate(analysis_payload)

    output = tmp_path / "many_risks.pdf"
    render_one_pager(analysis, output, generated_on=STAMP)

    assert "2 further risks identified" in _page_text(output)


# --------------------------------------------------------------------------- #
# Overflow guard
# --------------------------------------------------------------------------- #


def test_layout_fits_at_the_starting_font_size(analysis_result):
    from reportlab.lib.pagesizes import landscape, letter

    layout = _build_layout(
        analysis_result,
        landscape(letter),
        START_FONT_SIZE,
        "Acme Robotics",
        None,
        STAMP,
    )

    assert layout.fits
    assert layout.required <= layout.available


def test_ordinary_analysis_is_not_truncated(tmp_path, analysis_result):
    """Content of a normal size must survive the fit search intact."""
    output = tmp_path / "untruncated.pdf"
    render_one_pager(analysis_result, output, generated_on=STAMP)
    text = " ".join(_page_text(output).split())

    assert "…" not in text, "unexpected ellipsis: content was clipped"
    assert "cost advantage survives volume manufacturing" in text
    for question in analysis_result.top_diligence_questions:
        assert question in text


def test_fit_search_spends_text_budget_before_type_size(analysis_payload):
    """A long analysis should shrink type before clipping hard."""
    filler = "Extended narrative detail that keeps going and going. " * 12
    analysis_payload["executive_summary"]["investment_thesis"] = filler
    analysis_payload["top_diligence_questions"] = [filler] * 5
    analysis_payload["bull_case"] = filler
    analysis_payload["bear_case"] = filler
    analysis = AnalysisResult.model_validate(analysis_payload)

    from reportlab.lib.pagesizes import landscape, letter

    from pitch_analyzer.render import ACCEPTABLE_CLIP_SCALE, _fit_layout

    layout = _fit_layout(
        analysis, landscape(letter), "Acme Robotics", None, STAMP
    )

    assert layout.fits
    # The chosen candidate should use most of the page rather than bailing out
    # early onto a much tighter budget.
    assert layout.required > layout.available * 0.75
    assert ACCEPTABLE_CLIP_SCALE < 1.0  # guards the constant's meaning


def test_oversized_content_shrinks_but_still_fits(tmp_path, analysis_payload):
    # Long, multi-line strings everywhere force the guard to step the font down.
    filler = "Extended narrative detail. " * 12
    analysis_payload["executive_summary"]["investment_thesis"] = filler
    analysis_payload["bull_case"] = filler
    analysis_payload["bear_case"] = filler
    analysis_payload["executive_summary"]["top_strengths"] = [filler] * 3
    analysis_payload["executive_summary"]["top_concerns"] = [filler] * 3
    analysis_payload["top_diligence_questions"] = [filler] * 5
    for risk in analysis_payload["risks"]:
        risk["description"] = filler
        risk["mitigation"] = filler
    analysis = AnalysisResult.model_validate(analysis_payload)

    output = tmp_path / "dense.pdf"
    render_one_pager(analysis, output, generated_on=STAMP)

    assert _page_count(output) == 1


def test_overflow_raises_with_the_offending_section(tmp_path, analysis_result):
    from reportlab.lib.pagesizes import landscape, letter

    # A page too short for any font size in the range exercises the failure path.
    tiny_page = (landscape(letter)[0], 120.0)

    layout = _build_layout(
        analysis_result, tiny_page, MIN_FONT_SIZE, "Acme Robotics", None, STAMP
    )
    assert not layout.fits
    assert layout.overflow > 0
    assert layout.tallest_band

    import pitch_analyzer.render as render_module

    original = render_module.letter
    render_module.letter = (tiny_page[1], tiny_page[0])
    try:
        with pytest.raises(LayoutOverflowError) as excinfo:
            render_one_pager(analysis_result, tmp_path / "overflow.pdf")
    finally:
        render_module.letter = original

    message = str(excinfo.value)
    assert "5.5pt" in message
    assert "overflows by" in message


# --------------------------------------------------------------------------- #
# Score gradient
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("fraction", "dominant"),
    [(0.0, "red"), (0.5, "amber"), (1.0, "green")],
)
def test_score_gradient_runs_red_to_green(fraction, dominant):
    color = score_color(fraction)

    if dominant == "red":
        assert color.red > color.green
    elif dominant == "green":
        assert color.green > color.red
    else:
        assert color.red > 0.5 and color.green > 0.3


def test_score_gradient_clamps_out_of_range_input():
    assert score_color(-1.0).hexval() == score_color(0.0).hexval()
    assert score_color(5.0).hexval() == score_color(1.0).hexval()
